log:
  # "debug" "info" "warn" "error"
  level: "error"
  file: "/var/log/mosdns.log"
api:
  http: 0.0.0.0:9091
include: []
plugins:
  - tag: antiAd
    type: domain_set
    args:
      files:
        - "./rule/anti-ad.txt"
  - tag: ad
    type: domain_set
    args:
      files:
        - "./rule/ad.txt"
  - tag: awaAd
    type: domain_set
    args:
      files:
        - "./rule/awa-ad.txt"
  - tag: cnip
    type: ip_set
    args:
      files:
        - "./rule/geoip.txt"

  - tag: hosts
    type: hosts
    args:
      entries:
        - "mbp.mylocal.com 192.168.1.5"
  - tag: lazy_cache
    type: cache
    args:
      size: 4000
      lazy_cache_ttl: 86400
      dump_file: ./cache.dump
      dump_interval: 600

  - tag: ali_dns
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: ali_doh1
          addr: https://223.5.5.5/dns-query
        - tag: ali_doh2
          addr: https://223.6.6.6/dns-query
        - tag: ali_dot
          addr: tls://223.5.5.5
  - tag: tencent_dns
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: tencent_doh1
          addr: https://1.12.12.12/dns-query
        - tag: tencent_doh2
          addr: https://120.53.53.53/dns-query
        - tag: tencent_dot
          addr: tls://1.12.12.12
          enable_pipeline: true

  - tag: forward_local
    type: fallback
    args:
      primary: ali_dns
      secondary: tencent_dns
      threshold: 500
      always_standby: true

  - tag: cf_dns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: cf_doh
          addr: https://1.1.1.1/dns-query
        - tag: cf_dot
          addr: tls://1.1.1.1
          enable_pipeline: true
  - tag: open_dns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: open_doh
          addr: https://208.67.222.222/dns-query
        - tag: opendns_dot
          addr: tls://208.67.222.222
          enable_pipeline: true

  - tag: forward_remote
    type: fallback
    args:
      primary: cf_dns
      secondary: open_dns
      threshold: 700
      always_standby: true

  - tag: accept_resp
    type: sequence
    args:
      - matches: "!has_resp"
        exec: return
      - exec: accept
  - tag: reject_resp
    type: sequence
    args:
      # - matches: "has_resp"
      #   exec: return
      - exec: "query_summary no resp"
      - exec: reject 5

  - tag: local_seq
    type: sequence
    args:
      - exec: "query_summary local dns"
      - exec: "$forward_local"
      - matches: "!has_resp"
        exec: return
      - matches: "!resp_ip $cnip"
        exec: return
      - exec: accept

  - tag: remote_seq
    type: sequence
    args:
      - exec: "query_summary remote dns"
      - exec: "$forward_remote"
      - exec: jump accept_resp
      - exec: jump reject_resp

  - tag: block_seq
    type: sequence
    args:
      - matches: "qtype 12 65"
        exec: mark 1
      - matches: "qname $antiAd $ad $awaAd"
        exec: mark 1
      - matches: "!mark 1"
        exec: return
      - exec: "query_summary block dns"
      - exec: reject 3

  - tag: main_sequence
    type: sequence
    args:
      - exec: "$hosts"
      - exec: jump accept_resp
      - exec: "$lazy_cache"
      - exec: jump accept_resp
      - exec: jump block_seq
      - exec: prefer_ipv4
      - exec: jump local_seq
      - exec: goto remote_seq
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"
  # - tag: tcp_server
  #   type: tcp_server
  #   args:
  #     entry: main_sequence
  #     listen: ":5335"
