name: update
on: 
  push:
    branches:
      master
  schedule:
    - cron: '0 0 * * 1'
jobs:
  rule-update:
    name: update rule
    if: github.actor == 'wzp9708'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: run update script
        run: ./init.sh
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Add changes to Git
        run: |
          git add .
          git commit -m "update rules"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push