name: update
on: 
  push:
    branches:
      master
  schedule:
    - cron: '0 0 * * 1'
jobs:
  rule-update:
    name: update rule
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
        - name: run update script
          run: ./init.sh